// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package job

import (
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIHandler creates a new instance of MockIHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIHandler {
	mock := &MockIHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIHandler is an autogenerated mock type for the IHandler type
type MockIHandler struct {
	mock.Mock
}

type MockIHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIHandler) EXPECT() *MockIHandler_Expecter {
	return &MockIHandler_Expecter{mock: &_m.Mock}
}

// GetContractAccount provides a mock function for the type MockIHandler
func (_mock *MockIHandler) GetContractAccount(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockIHandler_GetContractAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContractAccount'
type MockIHandler_GetContractAccount_Call struct {
	*mock.Call
}

// GetContractAccount is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockIHandler_Expecter) GetContractAccount(ctx interface{}) *MockIHandler_GetContractAccount_Call {
	return &MockIHandler_GetContractAccount_Call{Call: _e.mock.On("GetContractAccount", ctx)}
}

func (_c *MockIHandler_GetContractAccount_Call) Run(run func(ctx *gin.Context)) *MockIHandler_GetContractAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHandler_GetContractAccount_Call) Return() *MockIHandler_GetContractAccount_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIHandler_GetContractAccount_Call) RunAndReturn(run func(ctx *gin.Context)) *MockIHandler_GetContractAccount_Call {
	_c.Run(run)
	return _c
}

// GetHolidays provides a mock function for the type MockIHandler
func (_mock *MockIHandler) GetHolidays(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockIHandler_GetHolidays_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHolidays'
type MockIHandler_GetHolidays_Call struct {
	*mock.Call
}

// GetHolidays is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockIHandler_Expecter) GetHolidays(ctx interface{}) *MockIHandler_GetHolidays_Call {
	return &MockIHandler_GetHolidays_Call{Call: _e.mock.On("GetHolidays", ctx)}
}

func (_c *MockIHandler_GetHolidays_Call) Run(run func(ctx *gin.Context)) *MockIHandler_GetHolidays_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHandler_GetHolidays_Call) Return() *MockIHandler_GetHolidays_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIHandler_GetHolidays_Call) RunAndReturn(run func(ctx *gin.Context)) *MockIHandler_GetHolidays_Call {
	_c.Run(run)
	return _c
}

// GetJobs provides a mock function for the type MockIHandler
func (_mock *MockIHandler) GetJobs(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockIHandler_GetJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobs'
type MockIHandler_GetJobs_Call struct {
	*mock.Call
}

// GetJobs is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockIHandler_Expecter) GetJobs(ctx interface{}) *MockIHandler_GetJobs_Call {
	return &MockIHandler_GetJobs_Call{Call: _e.mock.On("GetJobs", ctx)}
}

func (_c *MockIHandler_GetJobs_Call) Run(run func(ctx *gin.Context)) *MockIHandler_GetJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHandler_GetJobs_Call) Return() *MockIHandler_GetJobs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIHandler_GetJobs_Call) RunAndReturn(run func(ctx *gin.Context)) *MockIHandler_GetJobs_Call {
	_c.Run(run)
	return _c
}
