// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package holiday

import (
	"app/internal/model"
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Fetch(offset time.Time) ([]model.Holiday, error) {
	ret := _mock.Called(offset)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []model.Holiday
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) ([]model.Holiday, error)); ok {
		return returnFunc(offset)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time) []model.Holiday); ok {
		r0 = returnFunc(offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Holiday)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = returnFunc(offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockIRepository_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - offset time.Time
func (_e *MockIRepository_Expecter) Fetch(offset interface{}) *MockIRepository_Fetch_Call {
	return &MockIRepository_Fetch_Call{Call: _e.mock.On("Fetch", offset)}
}

func (_c *MockIRepository_Fetch_Call) Run(run func(offset time.Time)) *MockIRepository_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRepository_Fetch_Call) Return(holidays []model.Holiday, err error) *MockIRepository_Fetch_Call {
	_c.Call.Return(holidays, err)
	return _c
}

func (_c *MockIRepository_Fetch_Call) RunAndReturn(run func(offset time.Time) ([]model.Holiday, error)) *MockIRepository_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAll provides a mock function for the type MockIRepository
func (_mock *MockIRepository) FetchAll() ([]model.Holiday, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchAll")
	}

	var r0 []model.Holiday
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Holiday, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Holiday); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Holiday)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_FetchAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAll'
type MockIRepository_FetchAll_Call struct {
	*mock.Call
}

// FetchAll is a helper method to define mock.On call
func (_e *MockIRepository_Expecter) FetchAll() *MockIRepository_FetchAll_Call {
	return &MockIRepository_FetchAll_Call{Call: _e.mock.On("FetchAll")}
}

func (_c *MockIRepository_FetchAll_Call) Run(run func()) *MockIRepository_FetchAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIRepository_FetchAll_Call) Return(holidays []model.Holiday, err error) *MockIRepository_FetchAll_Call {
	_c.Call.Return(holidays, err)
	return _c
}

func (_c *MockIRepository_FetchAll_Call) RunAndReturn(run func() ([]model.Holiday, error)) *MockIRepository_FetchAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIService creates a new instance of MockIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIService {
	mock := &MockIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIService is an autogenerated mock type for the IService type
type MockIService struct {
	mock.Mock
}

type MockIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIService) EXPECT() *MockIService_Expecter {
	return &MockIService_Expecter{mock: &_m.Mock}
}

// FetchHolidays provides a mock function for the type MockIService
func (_mock *MockIService) FetchHolidays(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchHolidays")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIService_FetchHolidays_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchHolidays'
type MockIService_FetchHolidays_Call struct {
	*mock.Call
}

// FetchHolidays is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIService_Expecter) FetchHolidays(ctx interface{}) *MockIService_FetchHolidays_Call {
	return &MockIService_FetchHolidays_Call{Call: _e.mock.On("FetchHolidays", ctx)}
}

func (_c *MockIService_FetchHolidays_Call) Run(run func(ctx context.Context)) *MockIService_FetchHolidays_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIService_FetchHolidays_Call) Return(err error) *MockIService_FetchHolidays_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIService_FetchHolidays_Call) RunAndReturn(run func(ctx context.Context) error) *MockIService_FetchHolidays_Call {
	_c.Call.Return(run)
	return _c
}
