// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package scheduler

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIHandler creates a new instance of MockIHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIHandler {
	mock := &MockIHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIHandler is an autogenerated mock type for the IHandler type
type MockIHandler struct {
	mock.Mock
}

type MockIHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIHandler) EXPECT() *MockIHandler_Expecter {
	return &MockIHandler_Expecter{mock: &_m.Mock}
}

// AddFunc provides a mock function for the type MockIHandler
func (_mock *MockIHandler) AddFunc(crontab string, fn func()) error {
	ret := _mock.Called(crontab, fn)

	if len(ret) == 0 {
		panic("no return value specified for AddFunc")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, func()) error); ok {
		r0 = returnFunc(crontab, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIHandler_AddFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFunc'
type MockIHandler_AddFunc_Call struct {
	*mock.Call
}

// AddFunc is a helper method to define mock.On call
//   - crontab string
//   - fn func()
func (_e *MockIHandler_Expecter) AddFunc(crontab interface{}, fn interface{}) *MockIHandler_AddFunc_Call {
	return &MockIHandler_AddFunc_Call{Call: _e.mock.On("AddFunc", crontab, fn)}
}

func (_c *MockIHandler_AddFunc_Call) Run(run func(crontab string, fn func())) *MockIHandler_AddFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func()
		if args[1] != nil {
			arg1 = args[1].(func())
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIHandler_AddFunc_Call) Return(err error) *MockIHandler_AddFunc_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIHandler_AddFunc_Call) RunAndReturn(run func(crontab string, fn func()) error) *MockIHandler_AddFunc_Call {
	_c.Call.Return(run)
	return _c
}

// MasterDataSync provides a mock function for the type MockIHandler
func (_mock *MockIHandler) MasterDataSync() {
	_mock.Called()
	return
}

// MockIHandler_MasterDataSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MasterDataSync'
type MockIHandler_MasterDataSync_Call struct {
	*mock.Call
}

// MasterDataSync is a helper method to define mock.On call
func (_e *MockIHandler_Expecter) MasterDataSync() *MockIHandler_MasterDataSync_Call {
	return &MockIHandler_MasterDataSync_Call{Call: _e.mock.On("MasterDataSync")}
}

func (_c *MockIHandler_MasterDataSync_Call) Run(run func()) *MockIHandler_MasterDataSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIHandler_MasterDataSync_Call) Return() *MockIHandler_MasterDataSync_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIHandler_MasterDataSync_Call) RunAndReturn(run func()) *MockIHandler_MasterDataSync_Call {
	_c.Run(run)
	return _c
}

// SyncHolidays provides a mock function for the type MockIHandler
func (_mock *MockIHandler) SyncHolidays() {
	_mock.Called()
	return
}

// MockIHandler_SyncHolidays_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncHolidays'
type MockIHandler_SyncHolidays_Call struct {
	*mock.Call
}

// SyncHolidays is a helper method to define mock.On call
func (_e *MockIHandler_Expecter) SyncHolidays() *MockIHandler_SyncHolidays_Call {
	return &MockIHandler_SyncHolidays_Call{Call: _e.mock.On("SyncHolidays")}
}

func (_c *MockIHandler_SyncHolidays_Call) Run(run func()) *MockIHandler_SyncHolidays_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIHandler_SyncHolidays_Call) Return() *MockIHandler_SyncHolidays_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIHandler_SyncHolidays_Call) RunAndReturn(run func()) *MockIHandler_SyncHolidays_Call {
	_c.Run(run)
	return _c
}
