// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rediz

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// GetLatestOffset provides a mock function for the type MockIRepository
func (_mock *MockIRepository) GetLatestOffset(ctx context.Context, key string) (time.Time, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestOffset")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (time.Time, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) time.Time); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_GetLatestOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestOffset'
type MockIRepository_GetLatestOffset_Call struct {
	*mock.Call
}

// GetLatestOffset is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockIRepository_Expecter) GetLatestOffset(ctx interface{}, key interface{}) *MockIRepository_GetLatestOffset_Call {
	return &MockIRepository_GetLatestOffset_Call{Call: _e.mock.On("GetLatestOffset", ctx, key)}
}

func (_c *MockIRepository_GetLatestOffset_Call) Run(run func(ctx context.Context, key string)) *MockIRepository_GetLatestOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_GetLatestOffset_Call) Return(time1 time.Time, err error) *MockIRepository_GetLatestOffset_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *MockIRepository_GetLatestOffset_Call) RunAndReturn(run func(ctx context.Context, key string) (time.Time, error)) *MockIRepository_GetLatestOffset_Call {
	_c.Call.Return(run)
	return _c
}

// GetValueByHashField provides a mock function for the type MockIRepository
func (_mock *MockIRepository) GetValueByHashField(ctx context.Context, keySuffix string, field string) (string, error) {
	ret := _mock.Called(ctx, keySuffix, field)

	if len(ret) == 0 {
		panic("no return value specified for GetValueByHashField")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, keySuffix, field)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, keySuffix, field)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, keySuffix, field)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_GetValueByHashField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValueByHashField'
type MockIRepository_GetValueByHashField_Call struct {
	*mock.Call
}

// GetValueByHashField is a helper method to define mock.On call
//   - ctx context.Context
//   - keySuffix string
//   - field string
func (_e *MockIRepository_Expecter) GetValueByHashField(ctx interface{}, keySuffix interface{}, field interface{}) *MockIRepository_GetValueByHashField_Call {
	return &MockIRepository_GetValueByHashField_Call{Call: _e.mock.On("GetValueByHashField", ctx, keySuffix, field)}
}

func (_c *MockIRepository_GetValueByHashField_Call) Run(run func(ctx context.Context, keySuffix string, field string)) *MockIRepository_GetValueByHashField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIRepository_GetValueByHashField_Call) Return(s string, err error) *MockIRepository_GetValueByHashField_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIRepository_GetValueByHashField_Call) RunAndReturn(run func(ctx context.Context, keySuffix string, field string) (string, error)) *MockIRepository_GetValueByHashField_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Set(ctx context.Context, keySuffix string, value any, expiresIn time.Duration) error {
	ret := _mock.Called(ctx, keySuffix, value, expiresIn)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) error); ok {
		r0 = returnFunc(ctx, keySuffix, value, expiresIn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockIRepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - keySuffix string
//   - value any
//   - expiresIn time.Duration
func (_e *MockIRepository_Expecter) Set(ctx interface{}, keySuffix interface{}, value interface{}, expiresIn interface{}) *MockIRepository_Set_Call {
	return &MockIRepository_Set_Call{Call: _e.mock.On("Set", ctx, keySuffix, value, expiresIn)}
}

func (_c *MockIRepository_Set_Call) Run(run func(ctx context.Context, keySuffix string, value any, expiresIn time.Duration)) *MockIRepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIRepository_Set_Call) Return(err error) *MockIRepository_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_Set_Call) RunAndReturn(run func(ctx context.Context, keySuffix string, value any, expiresIn time.Duration) error) *MockIRepository_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetGlobalThreePhase provides a mock function for the type MockIRepository
func (_mock *MockIRepository) SetGlobalThreePhase(ctx context.Context, keySuffix string, value bool) error {
	ret := _mock.Called(ctx, keySuffix, value)

	if len(ret) == 0 {
		panic("no return value specified for SetGlobalThreePhase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, keySuffix, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_SetGlobalThreePhase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetGlobalThreePhase'
type MockIRepository_SetGlobalThreePhase_Call struct {
	*mock.Call
}

// SetGlobalThreePhase is a helper method to define mock.On call
//   - ctx context.Context
//   - keySuffix string
//   - value bool
func (_e *MockIRepository_Expecter) SetGlobalThreePhase(ctx interface{}, keySuffix interface{}, value interface{}) *MockIRepository_SetGlobalThreePhase_Call {
	return &MockIRepository_SetGlobalThreePhase_Call{Call: _e.mock.On("SetGlobalThreePhase", ctx, keySuffix, value)}
}

func (_c *MockIRepository_SetGlobalThreePhase_Call) Run(run func(ctx context.Context, keySuffix string, value bool)) *MockIRepository_SetGlobalThreePhase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIRepository_SetGlobalThreePhase_Call) Return(err error) *MockIRepository_SetGlobalThreePhase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_SetGlobalThreePhase_Call) RunAndReturn(run func(ctx context.Context, keySuffix string, value bool) error) *MockIRepository_SetGlobalThreePhase_Call {
	_c.Call.Return(run)
	return _c
}

// SetLatestOffset provides a mock function for the type MockIRepository
func (_mock *MockIRepository) SetLatestOffset(ctx context.Context, key string, offset time.Time) error {
	ret := _mock.Called(ctx, key, offset)

	if len(ret) == 0 {
		panic("no return value specified for SetLatestOffset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, key, offset)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_SetLatestOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLatestOffset'
type MockIRepository_SetLatestOffset_Call struct {
	*mock.Call
}

// SetLatestOffset is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - offset time.Time
func (_e *MockIRepository_Expecter) SetLatestOffset(ctx interface{}, key interface{}, offset interface{}) *MockIRepository_SetLatestOffset_Call {
	return &MockIRepository_SetLatestOffset_Call{Call: _e.mock.On("SetLatestOffset", ctx, key, offset)}
}

func (_c *MockIRepository_SetLatestOffset_Call) Run(run func(ctx context.Context, key string, offset time.Time)) *MockIRepository_SetLatestOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIRepository_SetLatestOffset_Call) Return(err error) *MockIRepository_SetLatestOffset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_SetLatestOffset_Call) RunAndReturn(run func(ctx context.Context, key string, offset time.Time) error) *MockIRepository_SetLatestOffset_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Upsert(ctx context.Context, keySuffix string, field string, value any) error {
	ret := _mock.Called(ctx, keySuffix, field, value)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, any) error); ok {
		r0 = returnFunc(ctx, keySuffix, field, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockIRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - keySuffix string
//   - field string
//   - value any
func (_e *MockIRepository_Expecter) Upsert(ctx interface{}, keySuffix interface{}, field interface{}, value interface{}) *MockIRepository_Upsert_Call {
	return &MockIRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, keySuffix, field, value)}
}

func (_c *MockIRepository_Upsert_Call) Run(run func(ctx context.Context, keySuffix string, field string, value any)) *MockIRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIRepository_Upsert_Call) Return(err error) *MockIRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, keySuffix string, field string, value any) error) *MockIRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
