// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package multiply

import (
	"app/internal/model"
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Fetch(offset time.Time) ([]model.ZDMI, error) {
	ret := _mock.Called(offset)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []model.ZDMI
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) ([]model.ZDMI, error)); ok {
		return returnFunc(offset)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time) []model.ZDMI); ok {
		r0 = returnFunc(offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ZDMI)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = returnFunc(offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockIRepository_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - offset time.Time
func (_e *MockIRepository_Expecter) Fetch(offset interface{}) *MockIRepository_Fetch_Call {
	return &MockIRepository_Fetch_Call{Call: _e.mock.On("Fetch", offset)}
}

func (_c *MockIRepository_Fetch_Call) Run(run func(offset time.Time)) *MockIRepository_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRepository_Fetch_Call) Return(zDMIs []model.ZDMI, err error) *MockIRepository_Fetch_Call {
	_c.Call.Return(zDMIs, err)
	return _c
}

func (_c *MockIRepository_Fetch_Call) RunAndReturn(run func(offset time.Time) ([]model.ZDMI, error)) *MockIRepository_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAll provides a mock function for the type MockIRepository
func (_mock *MockIRepository) FetchAll() ([]model.ZDMI, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchAll")
	}

	var r0 []model.ZDMI
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.ZDMI, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.ZDMI); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ZDMI)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_FetchAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAll'
type MockIRepository_FetchAll_Call struct {
	*mock.Call
}

// FetchAll is a helper method to define mock.On call
func (_e *MockIRepository_Expecter) FetchAll() *MockIRepository_FetchAll_Call {
	return &MockIRepository_FetchAll_Call{Call: _e.mock.On("FetchAll")}
}

func (_c *MockIRepository_FetchAll_Call) Run(run func()) *MockIRepository_FetchAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIRepository_FetchAll_Call) Return(zDMIs []model.ZDMI, err error) *MockIRepository_FetchAll_Call {
	_c.Call.Return(zDMIs, err)
	return _c
}

func (_c *MockIRepository_FetchAll_Call) RunAndReturn(run func() ([]model.ZDMI, error)) *MockIRepository_FetchAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIService creates a new instance of MockIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIService {
	mock := &MockIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIService is an autogenerated mock type for the IService type
type MockIService struct {
	mock.Mock
}

type MockIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIService) EXPECT() *MockIService_Expecter {
	return &MockIService_Expecter{mock: &_m.Mock}
}

// FetchMasterData provides a mock function for the type MockIService
func (_mock *MockIService) FetchMasterData(ctx context.Context, contractAccount *string) (model.HashValues, error) {
	ret := _mock.Called(ctx, contractAccount)

	if len(ret) == 0 {
		panic("no return value specified for FetchMasterData")
	}

	var r0 model.HashValues
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string) (model.HashValues, error)); ok {
		return returnFunc(ctx, contractAccount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string) model.HashValues); ok {
		r0 = returnFunc(ctx, contractAccount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.HashValues)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = returnFunc(ctx, contractAccount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_FetchMasterData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchMasterData'
type MockIService_FetchMasterData_Call struct {
	*mock.Call
}

// FetchMasterData is a helper method to define mock.On call
//   - ctx context.Context
//   - contractAccount *string
func (_e *MockIService_Expecter) FetchMasterData(ctx interface{}, contractAccount interface{}) *MockIService_FetchMasterData_Call {
	return &MockIService_FetchMasterData_Call{Call: _e.mock.On("FetchMasterData", ctx, contractAccount)}
}

func (_c *MockIService_FetchMasterData_Call) Run(run func(ctx context.Context, contractAccount *string)) *MockIService_FetchMasterData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_FetchMasterData_Call) Return(hashValues model.HashValues, err error) *MockIService_FetchMasterData_Call {
	_c.Call.Return(hashValues, err)
	return _c
}

func (_c *MockIService_FetchMasterData_Call) RunAndReturn(run func(ctx context.Context, contractAccount *string) (model.HashValues, error)) *MockIService_FetchMasterData_Call {
	_c.Call.Return(run)
	return _c
}
