// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package recal

import (
	"app/internal/model"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIService creates a new instance of MockIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIService {
	mock := &MockIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIService is an autogenerated mock type for the IService type
type MockIService struct {
	mock.Mock
}

type MockIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIService) EXPECT() *MockIService_Expecter {
	return &MockIService_Expecter{mock: &_m.Mock}
}

// CheckMasterDataExisting provides a mock function for the type MockIService
func (_mock *MockIService) CheckMasterDataExisting(ctx context.Context, datum model.ZDMI) (model.DifferenceDates, error) {
	ret := _mock.Called(ctx, datum)

	if len(ret) == 0 {
		panic("no return value specified for CheckMasterDataExisting")
	}

	var r0 model.DifferenceDates
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ZDMI) (model.DifferenceDates, error)); ok {
		return returnFunc(ctx, datum)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ZDMI) model.DifferenceDates); ok {
		r0 = returnFunc(ctx, datum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.DifferenceDates)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.ZDMI) error); ok {
		r1 = returnFunc(ctx, datum)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_CheckMasterDataExisting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckMasterDataExisting'
type MockIService_CheckMasterDataExisting_Call struct {
	*mock.Call
}

// CheckMasterDataExisting is a helper method to define mock.On call
//   - ctx context.Context
//   - datum model.ZDMI
func (_e *MockIService_Expecter) CheckMasterDataExisting(ctx interface{}, datum interface{}) *MockIService_CheckMasterDataExisting_Call {
	return &MockIService_CheckMasterDataExisting_Call{Call: _e.mock.On("CheckMasterDataExisting", ctx, datum)}
}

func (_c *MockIService_CheckMasterDataExisting_Call) Run(run func(ctx context.Context, datum model.ZDMI)) *MockIService_CheckMasterDataExisting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ZDMI
		if args[1] != nil {
			arg1 = args[1].(model.ZDMI)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_CheckMasterDataExisting_Call) Return(differenceDates model.DifferenceDates, err error) *MockIService_CheckMasterDataExisting_Call {
	_c.Call.Return(differenceDates, err)
	return _c
}

func (_c *MockIService_CheckMasterDataExisting_Call) RunAndReturn(run func(ctx context.Context, datum model.ZDMI) (model.DifferenceDates, error)) *MockIService_CheckMasterDataExisting_Call {
	_c.Call.Return(run)
	return _c
}
