// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kafka

import (
	"github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIService creates a new instance of MockIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIService {
	mock := &MockIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIService is an autogenerated mock type for the IService type
type MockIService struct {
	mock.Mock
}

type MockIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIService) EXPECT() *MockIService_Expecter {
	return &MockIService_Expecter{mock: &_m.Mock}
}

// Produces provides a mock function for the type MockIService
func (_mock *MockIService) Produces(messages []*sarama.ProducerMessage) error {
	ret := _mock.Called(messages)

	if len(ret) == 0 {
		panic("no return value specified for Produces")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*sarama.ProducerMessage) error); ok {
		r0 = returnFunc(messages)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIService_Produces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Produces'
type MockIService_Produces_Call struct {
	*mock.Call
}

// Produces is a helper method to define mock.On call
//   - messages []*sarama.ProducerMessage
func (_e *MockIService_Expecter) Produces(messages interface{}) *MockIService_Produces_Call {
	return &MockIService_Produces_Call{Call: _e.mock.On("Produces", messages)}
}

func (_c *MockIService_Produces_Call) Run(run func(messages []*sarama.ProducerMessage)) *MockIService_Produces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*sarama.ProducerMessage
		if args[0] != nil {
			arg0 = args[0].([]*sarama.ProducerMessage)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIService_Produces_Call) Return(err error) *MockIService_Produces_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIService_Produces_Call) RunAndReturn(run func(messages []*sarama.ProducerMessage) error) *MockIService_Produces_Call {
	_c.Call.Return(run)
	return _c
}
